version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest

    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "801:80/tcp"

    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: sudhir

    volumes:
      - '/etc/pihole/etc-pihole:/etc/pihole'
      - '/etc/pihole/etc-dnsmasq.d:/etc/dnsmasq.d' 

    networks:
      - macvlan   
    
    cap_add:
      - NET_ADMIN # Recommended bu

networks:
  macvlan:
    external: true