version: '3'
services:
  samba:
    image: 'dperson/samba'
    restart: unless-stopped
    ports:
      - '139:139'
      - '445:445'
    volumes:
      - /mnt/hardisk:/share
    environment:
     PUID: 1000
     PGID: 1000
     USERID: 1000
     GROUPID: 1000
     USER: guest;guest
     PERMISSIONS: true 
     SHARE: portainer;/share;yes;no;yes;guest
     PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      